// packages/knip/fixtures/plugins/svelte-styles/index.svelte
<script lang="ts">
  let title = 'Hello';
</script>

<h1>{title}</h1>

<style lang="scss">
  @use './styles/variables' as vars;

  h1 {
    color: vars.$primary;
  }
</style>

<style lang="less">
  @import './styles/theme';

  h1 {
    background: @accent;
  }
</style>

<style lang="stylus">
  @require './styles/animations'

  h1
    fade-in()
</style>

// packages/knip/fixtures/plugins/vue-styles/index.vue
<script setup lang="ts">
import { defineComponent } from 'vue';

defineComponent({});
</script>

<template>
  <div class="card">
    <h1>Hello</h1>
  </div>
</template>

<style lang="scss">
@use './styles/variables' as vars;

.card {
  color: vars.$primary;
}
</style>

<style lang="less">
@import './styles/theme';

.card {
  background: @accent;
}
</style>

<style lang="stylus">
@require './styles/animations'

.card
  fade-in()
</style>
